### ISSUE TITLE
Wifi 

### ISSUE THREAD

**Issue by Hosseinbadr** [PGBSean/Latitude-3580-OpenCore#2]
How can connect wifi ?

**Comment by PGBSean** [comment]
The built-in Wi-Fi (Qualcomm) is not supported in macOS and is disabled by default. You need to use your Android phone to tether, or purchase a USB/PCIe Wi-Fi card that is supported within macOS.

**Comment by PGBSean** [comment]
If there isn't any questions you wanted to ask, I will kindly close this issue.
